### PR TITLE
Contributing with LocationNet model

### PR DESCRIPTION
**Pull request by menant**
## Model URL
https://s3.amazonaws.com/aws-bigdata-blog/artifacts/RN1015k500/RN1015k500.mlmodel
## Demo URL
https://github.com/awslabs/MXNet2CoreML_iOS_sample_app
## Descriptions
Predict the location where a picture was taken.
## Checklist

- [x] Only one item is in this pull request
- [x] The model info contains all the required fields
- [x] The demo project is compilable
- [x] Has proper reference

### CODE REVIEW

**Comment by menant** [comment]
Oops: I got 2 additions that went into the same pull request.
Hope it's ok...

**Comment by likedan** [comment]
All good.

**Comment by menant** [comment]
The Apache MXNet project released a converter tool today, to convert from MXNet to Core ML, hence my additions.

**Comment by likedan** [comment]
Exciting to see new supports for Core ML!

**Comment by menant** [comment]
I got this published today, although there wasn't really a place to reference it in your document. But still it's linked in my GitHub repo where the sample project is located.

https://aws.amazon.com/blogs/ai/bring-machine-learning-to-ios-apps-using-apache-mxnet-and-apple-core-ml/

**Comment by likedan** [comment]
I was you reference this link. https://aws.amazon.com/blogs/ai/estimating-the-location-of-images-using-mxnet-and-multimedia-commons-dataset-on-aws-ec2/. Do you with to reference both articles? I can definitely do that for you.

**Comment by menant** [comment]
This link you pasted is the most appropriate that I could find to serve as research paper / justification. It is a blog post that was written by the authors of the LocationNet model. I only converted that model from MXNet using our recently released tool, and created a sample iOS app to demonstrate its capabilities.

So I don't think it needs changing. Thanks for offering!  😊

**Pull request merged**
